name: CI

on:
  push:
    branches:
      - '**'

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    env:
      HEALTH_CHECK_RETRIES: 2
      HEALTH_CHECK_INTERVAL: 1
      NLTK_DATA: ${{ github.workspace }}/nltk_data  # Set NLTK data directory globally

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.*'

      - name: Create and activate virtual environment
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install --upgrade pip

      - name: Install dependencies in venv
        run: |
          source venv/bin/activate
          pip install -r requirements.txt
          pip install flake8

      - name: Download NLTK resources
        run: |
          source venv/bin/activate
          mkdir -p $NLTK_DATA
          python -m nltk.downloader -d $NLTK_DATA punkt stopwords

      - name: Run linter
        run: |
          source venv/bin/activate
          flake8 .

      - name: Run tests
        run: |
          source venv/bin/activate
          pytest

      - name: Cleanup unused resources
        run: |
          pip cache purge
          rm -rf .pytest_cache venv nltk_data
